import SideNav from '@/components/SideNav';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Providers from './providers';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className="bg-ctp-base">
                <Providers>
                    <div className="flex min-h-screen bg-ctp-base ">
                        <div className="flex w-full flex-row">
                            <SideNav />
                            <div className="h-full w-full pt-10">
                                {children}
                            </div>
                        </div>
                    </div>
                </Providers>
            </body>
        </html>
    );
}
